codesnippets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('', RedirectView.as_view(url='snippets/', permanent=False), name='home'),
]

snippets/urls.py
from django.urls import path

from . import views

app_name = 'snippets'

urlpatterns = [
    path('', views.SnippetList.as_view(), name='list'),
    path('tag/<str:tag>/', views.SnippetList.as_view(), name='by-tag'),
    path('create/', views.SnippetCreate.as_view(), name='create'),
    path('<int:pk>/', views.SnippetDetail.as_view(), name='detail'),
    path('<int:pk>/update/', views.SnippetUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.SnippetDelete.as_view(), name='delete'),
]

snippets/models.py
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse

TAG_MAX_LEN = 30
SNIPPET_MAX_TAGS = 5


class Snippet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, db_index=True)
    code = models.TextField()
    tags = ArrayField(models.CharField(max_length=TAG_MAX_LEN), size=SNIPPET_MAX_TAGS)
    published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'{self.id}: "{self.title}" by {self.user}'

    def get_absolute_url(self):
        """Returns snippet url to be used as redirect url for UpdateView"""
        return reverse('snippets:detail', kwargs={'pk': self.pk})


class Tag(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True)
    name = models.CharField(max_length=TAG_MAX_LEN, db_index=True)
    num_posts = models.IntegerField(default=0, db_index=True)

    def __str__(self):
        return f'{self.id}: "{self.name}" added by {self.user}'

snippets/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from .models import Snippet


class SnippetCreate(CreateView):
    template_name = 'snippets/snippet_form.html'
    model = Snippet
    fields = ['title', 'code', 'tags', 'published']

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.instance.user = self.request.user
        return super().form_valid(form)


class SnippetUpdate(UpdateView):
    template_name = 'snippets/snippet_form.html'
    model = Snippet
    fields = ['title', 'code', 'tags', 'published']


class SnippetDelete(DeleteView):
    template_name = 'snippets/snippet_delete.html'
    model = Snippet
    success_url = reverse_lazy('snippets:list')


class SnippetDetail(DetailView):
    template_name = 'snippets/snippet_detail.html'
    model = Snippet
    context_object_name = 'snippet'


class SnippetList(ListView):
    template_name = 'snippets/snippet_list.html'
    context_object_name = 'snippets'
    paginate_by = 25  # This allows passing ?page=x to the url

    def get_queryset(self):
        qs = Snippet.objects.all()
        # In the case this view was triggered by a visit to /snippets/tags/TAG/
        # self.kwargs['tag'] will have the tag. We use it to filter the queryset
        if 'tag' in self.kwargs:
            qs = qs.filter(tags__contains=[self.kwargs['tag']])
        return qs.order_by('-created_at')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>{% block title %}Code Snippets{% endblock %}</title>
</head>
<body>
<div class="container">
    <nav class="navbar static-top navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url "home" %}">
            <img src="http://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
        </a>
        <!-- Links -->
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "snippets:create" %}">Upload Snippet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "logout" %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "login" %}">Login</a>
                </li>
                {#            Todo: add navbar item for signup once implemented#}
                {#            <li class="nav-item">#}
                {#                <a class="nav-link" href="{% url "signup" %}">Signup</a>#}
                {#            </li>#}
            {% endif %}
        </ul>
    </nav>
    {% block content %}{% endblock content %}
</div>
<!-- Bootstrap JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

templates/snippets/snippet_delete.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "#{{ snippet.id }} - {{ snippet.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/snippets/snippet_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <!-- Title -->
        <h3><a href="{% url "snippets:detail" snippet.id %}">#{{ snippet.id }} - {{ snippet.title }}</a></h3>

        <!-- Code -->
        <div class="p-2 border">
            <pre class="pre-scrollable"><code>{{ snippet.code }}</code></pre>
        </div>

        <!-- Tags -->
        <div class="py-1 my-1">
            {% for tag in snippet.tags %}
                <a class="btn btn-sm btn-outline-secondary" href="{% url "snippets:by-tag" tag %}">{{ tag }}</a>
            {% endfor %}
        </div>

        <!-- User and date -->
        <div class="my-1">
            <span>{{ snippet.user.username }} - {{ snippet.created_at }}</span>
        </div>

        <!-- Actions -->
        <div class="">
            <a class="btn btn-sm btn-info" href="{% url "snippets:update" snippet.id %}">Update</a>
            <a class="btn btn-sm btn-danger" href="{% url "snippets:delete" snippet.id %}">Delete</a>
        </div>
    </div>
{% endblock %}

templates/snippets/snippet_form.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        {% if snippet %}
            <input type="submit" class="btn btn-success" value="Save">
            <a class="btn btn-secondary" href="{% url "snippets:detail"  snippet.id %}">Cancel</a>
        {% else %}
            <input type="submit" value="Create">
        {% endif %}
    </form>
{% endblock %}

templates/snippets/snippet_list.html
{% extends "base.html" %}

{% block content %}
    <!-- Snippets list -->
    {% for snippet in snippets %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <!-- Title -->
            <h3><a href="{% url "snippets:detail" snippet.id %}">#{{ snippet.id }} - {{ snippet.title }}</a></h3>

            <!-- Code -->
            <div class="p-2 border">
                <pre class="pre-scrollable"><code>{{ snippet.code }}</code></pre>
            </div>

            <!-- Tags -->
            <div class="py-1">
                {% for tag in snippet.tags %}
                    <a class="btn btn-sm btn-outline-secondary" href="{% url "snippets:by-tag" tag %}">{{ tag }}</a>
                {% endfor %}
            </div>

            <!-- User and date -->
            <div class="my-1">
                <span>{{ snippet.user.username }} - {{ snippet.created_at }}</span>
            </div>
        </div>
    {% endfor %}

    <!-- Pagination -->
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            <li class="page-item active">
                <a class="page-link" href="#">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endblock %}